services:
  certbot:
    image: certbot/certbot:latest
    restart: always
    environment:
      - TSAPP_DOMAIN_NAME=${TSAPP_DOMAIN_NAME}
      - CERTBOT_SELFSIGNED=${CERTBOT_SELFSIGNED}
      - CERTBOT_EXTRA_DOMAIN_NAMES=${CERTBOT_EXTRA_DOMAIN_NAMES}
      - CERTBOT_RESTART_TIME=${CERTBOT_RESTART_TIME}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    networks:
      default_network:
        ipv4_address: ${CERTBOT_IP}
    volumes:
      - ../packages/${ALIAS}/configs/certbot/nginx.conf:/etc/nginx/nginx.conf
      - ../packages/${ALIAS}/configs/haproxy/wk/:/var/www/wk/
      - ../packages/${ALIAS}/configs/haproxy/ssl/:/home/ssl/
      - ../packages/${ALIAS}/configs/letsencrypt/:/etc/letsencrypt/
      - ../packages/${ALIAS}/logs/certbot/:/etc/nginx/logs/
      - ../packages/${ALIAS}/logs/letsencrypt/:/var/log/letsencrypt/
      - ../packages/${ALIAS}/bin/certbot.sh:/home/scripts/certbot.sh
    entrypoint: /home/scripts/certbot.sh
    ports:
      - "${CERTBOT_PORT}:80" # CERTBOT HTTP