services:
  sftp:
    image: atmoz/sftp
    networks:
      tsapp_net:
        ipv4_address: ${SFTP_IP}
    volumes:
      - ../:/home/tsapp/dev/
      - ../packages/${@ALIAS}/configs/sftp/users.conf:/etc/sftp/users.conf
    ports:
      - "${SFTP_PORT}:22"
