services:
  tsapp:
    image: typestackapp/tsapp:latest
    build:
      context: ./
      dockerfile: ./Dockerfile.${@ALIAS}.tsapp
    restart: always
    env_file: ${@ENV_DEFAULTS}
    networks:
      default_network:
        ipv4_address: ${TSAPP_IP}
    volumes: ${TSAPP_VOLUME}
    ports:
      - "${TSAPP_NEXT_PORT}:80"       # HTTP NEXT
      - "${TSAPP_API_PORT}:8000"      # HTTP API
      - "${TSAPP_GRAPHQL_PORT}:8002"  # HTTP GRAPHQL
    entrypoint: /tsapp/packages/${@ALIAS}/bin/tsapp.sh