services:
  haproxy:
    mem_limit: 3g
    image: haproxy:2.9.6
    restart: always
    user: root
    env_file: ${@DEFAULT_FILES}
    networks:
      default_network:
        ipv4_address: ${HAPROXY_IP}
    volumes:
      - ../packages/${@ALIAS}/codegen/haproxy/proxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ../packages/${@ALIAS}/logs/haproxy/:/var/log/
      - ../packages/${@ALIAS}/configs/haproxy/ssl/:/home/ssl/
      - ../packages/${@ALIAS}/bin/haproxy.sh:/home/scripts/haproxy.sh
    entrypoint: /home/scripts/haproxy.sh
    ports: ${HAPROXY_PORT}
